# NOTE: to be able to run CI define the following env variables:
# --WRPC_SW_REGISTRY_PATH - optional the path to the registry
# --WRPC_SW_RUNNER_TAG - optional tag of allowed runners

image: ${WRPC_SW_REGISTRY_PATH}ubuntu:22.04

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt update && apt upgrade -y
  - DEBIAN_FRONTEND=noninteractive TZ=Europe/Zurich apt -y install tzdata
  - apt install -y wget git make build-essential libreadline-dev locales gcc-arm-none-eabi
  - locale-gen en_US.UTF-8
  - mkdir -p cache/downloads && cd cache/downloads
  - wget -c https://gitlab.com/ohwr/project/wrpc-sw/-/wikis/uploads/9f9224d2249848ed3e854636de9c08dc/riscv-11.2-small.tgz
  - wget -c https://gitlab.com/ohwr/project/wr-cores/-/wikis/uploads/2776ce0ba43503d1486ae205b48fb450/lm32_host_64bit.tar.xz
  - cd ..
  - tar -xf downloads/riscv-11.2-small.tgz
  - tar -xf downloads/lm32_host_64bit.tar.xz
  - export CROSS_COMPILE_LM32=`pwd`/lm32-gcc-4.5.3/bin/lm32-elf-
  - export CROSS_COMPILE_RISCV=`pwd`/riscv-11.2-small/bin/riscv32-elf-
  - echo ${CROSS_COMPILE_LM32} ${CROSS_COMPILE_RISCV}
  - cd ${CI_PROJECT_DIR}
  #- PATH=/compilers/riscv-11.2-small/bin:/compilers/lm32-gcc-4.5.3/bin:$PATH
  # use the user who triggered a job to appear in binaries
  - echo "[user]" >  ~/.gitconfig
  - echo "    name = CI ${GITLAB_USER_NAME}" >>  ~/.gitconfig

stages:
- compile

make_wrpc_sw:
  stage: compile
  tags:
    - ${WRPC_SW_RUNNER_TAG}
  script:
  - make spec_defconfig
  - make
  artifacts:
    name: wrpc_sw_ci_${CI_JOB_NAME}_${CI_JOB_ID}
    paths:
    - wrc.elf
    - tools/wrpc
    - tools/wrpc-diags
    - tools/wrpc-dump
    - tools/wrpc-load
    - tools/wrpc-vuart
    - tools/mapper
  cache:
    key: wrpc-sw-download-cache
    paths:
      - cache/downloads

make_all:
  stage: compile
  tags:
    - ${WRPC_SW_RUNNER_TAG}
  script:
    # needed for ertm14 build
    - apt install -y libudev-dev
    - NPROC=$(grep -c ^processor /proc/cpuinfo)
    # to make compare_size.sh work
    - touch size_db.txt
    - echo "Using $NPROC parallel jobs".
    - GIT_HASH_START="HEAD~1" MAKEFLAGS="-j $NPROC" ./MAKEALL -c
  artifacts:
    name: wrpc_sw_ci_${CI_JOB_NAME}_${CI_JOB_ID}
    paths:
    - size_info.txt
    - ./*.elf
    - ./*.bin
  cache:
    key: wrpc-sw-download-cache
    paths:
      - cache/downloads

make_rt_cpu:
  stage: compile
  tags:
    - ${WRPC_SW_RUNNER_TAG}
  script:
  - make wr_switch_defconfig
  - make
  artifacts:
    name: wrpc_sw_ci_${CI_JOB_NAME}_${CI_JOB_ID}
    paths:
    - rt_cpu.elf
  cache:
    key: wrpc-sw-download-cache
    paths:
      - cache/downloads
