#ifndef __CHEBY__VUART_HOST_MAP__H__
#define __CHEBY__VUART_HOST_MAP__H__

#define VUART_HOST_MAP_SIZE 8 /* 0x8 */

/* Host VUART Tx register */
#define VUART_HOST_MAP_HOST_TDR 0x0UL
#define VUART_HOST_MAP_HOST_TDR_DATA_MASK 0xffUL
#define VUART_HOST_MAP_HOST_TDR_DATA_SHIFT 0
#define VUART_HOST_MAP_HOST_TDR_RDY 0x100UL
#define VUART_HOST_MAP_HOST_TDR_RDY_MASK 0x100UL
#define VUART_HOST_MAP_HOST_TDR_RDY_SHIFT 8

/* Host VUART Rx register */
#define VUART_HOST_MAP_HOST_RDR 0x4UL
#define VUART_HOST_MAP_HOST_RDR_DATA_MASK 0xffUL
#define VUART_HOST_MAP_HOST_RDR_DATA_SHIFT 0
#define VUART_HOST_MAP_HOST_RDR_RDY 0x100UL
#define VUART_HOST_MAP_HOST_RDR_RDY_MASK 0x100UL
#define VUART_HOST_MAP_HOST_RDR_RDY_SHIFT 8
#define VUART_HOST_MAP_HOST_RDR_COUNT_MASK 0x1fffe00UL
#define VUART_HOST_MAP_HOST_RDR_COUNT_SHIFT 9
#define VUART_HOST_MAP_HOST_RDR_ZERO_MASK 0xfe000000UL
#define VUART_HOST_MAP_HOST_RDR_ZERO_SHIFT 25
#define VUART_HOST_MAP_HOST_RDR_ZERO_PRESET 0x0UL

#ifndef __ASSEMBLER__
struct vuart_host_map {
  /* [0x0]: REG (rw) Host VUART Tx register */
  uint32_t HOST_TDR;

  /* [0x4]: REG (ro) Host VUART Rx register */
  uint32_t HOST_RDR;
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__VUART_HOST_MAP__H__ */
