#!/usr/bin/env python3
"""Generate the WRPC shell command list from the command registry."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

WRPC_ROOT = Path(__file__).resolve().parents[2]
SRC = WRPC_ROOT / "include/cmds.h"

COMMAND_RE = re.compile(
    r"^\s*WRC_COMMAND2\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*"
    r"([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*$"
)
SIMPLE_COMMAND_RE = re.compile(
    r"^\s*WRC_COMMAND\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*$"
)
IFDEF_RE = re.compile(r"^\s*#ifdef\s+([A-Za-z_][A-Za-z0-9_]*)\s*$")
IF_RE = re.compile(r"^\s*#if\s+(.+?)\s*$")
ENDIF_RE = re.compile(r"^\s*#endif\b")
BRIEF_RE = re.compile(r"^\s*/\*\*\s*@brief\s+(.*?)\s*\*/\s*$")
SHELL_DOC_RE = re.compile(r"/\*\*(.*?)\*/", re.DOTALL)
SHELL_COMMAND_RE = re.compile(r"^\s*@shellcommand\s+(\S+)\s*$")
SHELL_USAGE_RE = re.compile(r"^\s*@shellusage\s+(.+?)\s*$")
TAG_RE = re.compile(r"^\s*\*\s*@\S+")


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    for source, replacement in replacements.items():
        text = text.replace(source, replacement)
    return text.replace("[", "{[}").replace("]", "{]}")


def parse_commands(path: Path) -> list[dict[str, str]]:
    commands = []
    guards: list[str] = []
    brief = ""

    for raw_line in path.read_text().splitlines():
        if match := BRIEF_RE.match(raw_line):
            brief = match.group(1)
            continue
        if match := IFDEF_RE.match(raw_line):
            guards.append(match.group(1))
            continue
        if match := IF_RE.match(raw_line):
            guards.append(match.group(1))
            continue
        if ENDIF_RE.match(raw_line):
            if guards:
                guards.pop()
            continue

        match = COMMAND_RE.match(raw_line) or SIMPLE_COMMAND_RE.match(raw_line)
        if not match:
            continue
        if match.re is COMMAND_RE:
            name, function = match.groups()
        else:
            name = function = match.group(1)

        commands.append({
            "name": name,
            "function": function,
            "guard": ", ".join(guards),
            "brief": brief,
        })
        brief = ""

    return commands


def parse_shell_docs(directories: tuple[Path, ...]) -> dict[str, dict[str, object]]:
    documentation = {}

    for directory in directories:
        for path in sorted(directory.glob("*.c")):
            for block in SHELL_DOC_RE.findall(path.read_text()):
                command_match = None
                brief = ""
                usages = []
                current_usage = None

                for raw_line in block.splitlines():
                    line = raw_line.strip()
                    if line.startswith("*"):
                        line = line[1:].strip()
                    if match := SHELL_COMMAND_RE.match(line):
                        command_match = match.group(1)
                        continue
                    if line.startswith("@brief "):
                        brief = line[7:].strip()
                        continue
                    if match := SHELL_USAGE_RE.match(line):
                        current_usage = {"syntax": match.group(1), "description": []}
                        usages.append(current_usage)
                        continue
                    if current_usage is not None and line and not TAG_RE.match(line):
                        current_usage["description"].append(line)

                if command_match:
                    documentation[command_match] = {
                        "brief": brief,
                        "usages": usages,
                    }

    return documentation


def build_tex(commands: list[dict[str, str]], documentation: dict[str, dict[str, object]]) -> str:
    lines = [
        r"% This file is generated by generate_shell_commands.py.",
        r"\begin{description}",
    ]

    for command in commands:
        name = latex_escape(command["name"])
        command_doc = documentation.get(command["name"], {})
        details = latex_escape(command_doc.get("brief") or command["brief"])
        usages = command_doc.get("usages", [])
        bare_usage = next(
            (usage for usage in usages if usage["syntax"] == command["name"]),
            None,
        )
        if bare_usage and bare_usage["description"]:
            details = latex_escape(" ".join(bare_usage["description"]))
        if not details:
            function = latex_escape(command["function"])
            details = f"Implemented by \\texttt{{cmd\\_{function}}}."
        if command["guard"]:
            guard = latex_escape(command["guard"])
            details += f" Available when \\texttt{{{guard}}} is enabled."
        lines.extend([f"\\item[{name}] \\mbox{{}}", "", f"  {details}", ""])

        for usage in usages:
            if usage is bare_usage:
                continue
            syntax = latex_escape(usage["syntax"])
            description = " ".join(usage["description"])
            lines.extend([
                f"\\item[{syntax}] \\mbox{{}}",
                "",
                f"  {latex_escape(description)}",
                "",
            ])

    lines.extend([r"\end{description}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if not SRC.exists():
        raise SystemExit(f"Source file not found: {SRC}")

    documentation = parse_shell_docs(tuple(
        WRPC_ROOT / directory for directory in ("shell", "dev", "lib")
    ))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_tex(parse_commands(SRC), documentation))
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
